packages:
  - packages/*
  - website

catalogMode: prefer
strictPeerDependencies: false

catalog:
  '@nuxt/content': ^3.11.0
  '@nuxtjs/seo': ^3.4.0
  '@types/better-sqlite3': ^7.6.12
  '@types/node': ^22.0.0
  '@types/pg': ^8.11.0
  consola: ^3.4.2
  defu: ^6.1.4
  miniflare: ^4.20260128.0
  pathe: ^2.0.3
  tsx: ^4.0.0
catalogs:
  build:
    tsdown: ^0.15.0
  db:
    '@electric-sql/pglite': ^0.2.0
    '@libsql/client': ^0.14.0
    '@planetscale/database': ^1.19.0
    better-sqlite3: ^11.0.0
    mysql2: ^3.11.0
    pg: ^8.13.0
    sqlite3: ^5.1.7
  lint:
    '@antfu/eslint-config': ^4.0.0
    eslint: ^9.0.0
  nuxt:
    '@nuxt/fonts': ^0.13.0
    '@nuxt/icon': ^1.13.0
    '@nuxt/ui': ^4.4.0
    '@vueuse/core': ^14.1.0
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.3.0
    reka-ui: ^2.8.0
    tailwindcss: ^4.0.0
  test:
    vitest: ^3.0.0
  types:
    typescript: ^5.7.0
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sqlite3
