import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { capabilities, targets } from '../packages/data/src/index'

const capabilityIds = capabilities.map(c => c.id)
const targetIds = targets.map(t => t.id)

const typesContent = `// Auto-generated by scripts/generate-types.ts - do not edit manually
export type CapabilityId = ${capabilityIds.map(id => `'${id}'`).join(' | ')}

export type TargetId = ${targetIds.map(id => `'${id}'`).join(' | ')}
`

const outPath = resolve(import.meta.dirname, '../packages/data/src/generated.ts')
writeFileSync(outPath, typesContent)
console.log(`Types written to ${outPath}`)
